### ISSUE TITLE
Community Suggestion

### ISSUE THREAD

**Issue by TheEpicness9000** [JKPotato-Computer/SignMaker#10]
I have Discord, and I know a Discord server of road fanatics. They're a group of players who are working on a Minecraft mod named Traffic Control, and your signs have occasionally been used.

Perhaps you could open a Discord server of your own?

**Comment by JKPotato-Computer** [comment]
I don't have Discord.

Kidding, why would I not? I might start one if you and your "road fanatics" would like to :rofl: 
Let me know what yall think and I may start one, but give me a couple days since I gotta get school over with. I mean, I'm not in my 20s as of writing this sooo that connects the dots... :)

**Comment by JKPotato-Computer** [comment]
https://discord.gg/6UsjC7QM :)
