### ISSUE TITLE
Issues with the Shields

### ISSUE THREAD

**Issue by stevenjeter94** [JKPotato-Computer/SignMaker#3]
Hi. 

I stumbled upon this when searching for Kurumi's Sign Maker on the internet. I think this is a great project and I am looking forward to future updates. I did find an issue with it though. Upon creating a Sign and saving it in either of the supported formats, the shields do not show up. I only get a white outline of a box around the number that I chose for the route. This is with all shields that I tried. I tested this with Chrome and Edge with the same issue on both. 

Just wanted to let you know just in case you were not aware. Keep up the hard work. 

![Test](https://github.com/JKPotato-Computer/SignMaker/assets/145623051/e1ee5396-35d2-4916-85e2-c0af3e0c6000)

**Comment by JKPotato-Computer** [comment]
yeah... sorry bout that. honestly i haven't found a solution for the downloading sign part. trust me, i am still a beginner :p
but hey thanks for letting me know! i'll try to fix it, whenever i have the time to :)

(btw, here's an alternative method for now: hide the post and zoom into the signs, and take a screenshot - remove the background afterwards, and you have yourself the sign!)

hope you've enjoyed the program!

**Comment by stevenjeter94** [comment]
Yes, that's what I did. Saved the sign after making it by doing a screen grab. Then using Gimp to remove backgrounds.

Hopefully, you can figure out the issue. Great work so far though. Even though you're a beginner, you're doing better than I could manage.

I will for sure continue filling your work. You've got some talent for sure. Good Luck with your future endeavors.


Thanks,

Steven Jeter,
Professional Truck Driver

(812)391-8924
***@***.***
________________________________

**Comment by brisingraerowing** [comment]
[Here's how I made shields export in my fork](https://github.com/brisingraerowing/SignMaker/blob/master/js/main.js#L772-L808)

Basically I export to SVG, render to a Canvas, then export the Canvas to an Image.

**Comment by JKPotato-Computer** [comment]
Thanks @brisingraerowing! I've tried it on my local copy of the SignMaker for the next major update... if that ever comes out. Unfortunately, I come across the same issue as the post described above (probably because I am on localhost and not an actual web host?) Anyway, this is the sign I attempted to make:
![image](https://github.com/JKPotato-Computer/SignMaker/assets/100048313/8881ac85-2ea3-4cb2-811a-687f3f55e01e)

And this is the sign I ended up with:
![downloadedSign (5)](https://github.com/JKPotato-Computer/SignMaker/assets/100048313/54f7796c-adbb-4d22-984b-a7c344beeb23)

It might possibly work if I published this change early onto Github, so I'll probably try that later. Although, anyone can lend me a hand on how to make the image results bigger and take up the right size? They're just too small and blurry at the end! Attached is a link of the code snippet to download PNG files (that I totally didn't just rip off a part from yours... :wink:)
 - getFile() is just to grab the panel/post itself, attributed to parameter file in saveToPng(file)
 - isPreview is just a preview of the PNG, isSVG is making an SVG except I didn't use the right format to save it... oops
 - main system in saveToPng()
 - sorry if this code is heavily unoptimized :sweat:
```js
function getFile() {
	var screenshotTarget;
	var postClass;

	if (fileInfo.panel == -1) {
		screenshotTarget = document.querySelector("#postContainer");
	} else {
		screenshotTarget = document.getElementById("panel" + fileInfo.panel.toString());
	}


	return screenshotTarget;
}
	
const downloadFile = function(dataURL) {
	let a = document.createElement(`a`);
	a.setAttribute("href", dataURL);
	a.setAttribute("download", "downloadedSign.png");
	a.click();
	a.remove();
}
	
const saveToPng = function(file,isPreview,isSVG) {
	let svg = htmlToImage.toSvg(file);
	svg.then(function(dataUrl) {
		if (isSVG) {
			if (isPreview) {
				return dataUrl;
			}
			downloadFile(dataUrl);
			return;
		}
		let tmpCanvas = document.createElement("canvas");
		let ctx = tmpCanvas.getContext("2d");
	
		let tmpImg = new Image();
		tmpImg.addEventListener("load", onTempImageLoad);
		tmpImg.src = dataUrl;
		
		console.log(tmpImg.width, tmpImg.height);

		tmpCanvas.width = tmpCanvas.height = 512;

		// let targetImg = new Image();

		function onTempImageLoad(e) {
			tmpCanvas.width = e.target.width;
			tmpCanvas.height = e.target.height;

			ctx.drawImage(e.target, 0, 0);
			if (isPreview) {
				let targetImg = new Image();
				targetImg.src = tmpCanvas.toDataURL();
				return targetImg;
			} else {
				downloadFile(tmpCanvas.toDataURL());
			}
		};
			
	}).catch(function(error) {
		console.error("Error Saving!", error);
	});
}
```

**Comment by JKPotato-Computer** [comment]
Follow up: Tried it once more with changes in GitHub page, same result. Any ideas on why?

**Comment by brisingraerowing** [comment]
Might be related to the library you use. I use a different one.

**Comment by JKPotato-Computer** [comment]
I have some good news, the download signs mechanic has been fixed! It was because I used an object element instead of a image element for the shields, probably not supported by html-to-image. Here's the final result:

![image](https://github.com/JKPotato-Computer/SignMaker/assets/100048313/8cf7458f-6f6e-4ab2-8108-c01130fa0d42)
![downloadedSign (10)](https://github.com/JKPotato-Computer/SignMaker/assets/100048313/0ac8c033-8373-442f-b399-f8b62b2245d8)

Some problems I still want to be addressed:
- Panel is too small and should be enlarged, but I have no idea on how to do that...
- Image also has too large of a pixel size (there is more invisible pixels than actual sign) and should really only be the panel itself (or the post depending on configuration)
- Image does not carry over the enlarged first letters such as "South' or "East". This is also a problem  with your fork too, but if there was an alternative to this, would be nice to let me know aswell!
